#!/usr/bin/env python3
"""Knowledge as a vault of notes, not one file (ADR-0043).

A matter's durable knowledge lives in `knowledge/`: one Markdown note per
person, organization, event, topic, issue or filing, each with YAML
front matter that doubles as a link graph and a grep surface:

    ---
    title: Jane Roe
    type: person              # person | organization | event | topic | issue | filing
    aliases: [J. Roe, Roe]    # every name the record uses, misspellings included
    tags: [counsel]
    related: ["[[smith-v-roe]]", "[[2026-09-18-hearing]]"]
    sources:
      - path: assets/gmail/2026-01-02_letter.pdf
        pages: "3-4"
        note: what it shows
    date: 2026-09-18          # events only
    status: open              # issues only: open | resolved
    updated: 2026-09-07
    verified: machine         # machine | human
    ---

The layout is an Obsidian-compatible vault rooted at the matter
directory --- wikilinks resolve by filename stem, `aliases` and `tags`
are Obsidian's own keys --- so the vault opens cleanly in Obsidian with
backlinks and graph for a human reader. Nothing here depends on
Obsidian; agents read the same files with ripgrep and follow the same
links.

`KNOWLEDGE.md` at the matter root is the index, regenerated between two
markers by `index`. `derived/knowledge/entities.json` is a derived alias
index for the first tier of `sc find`.

Commands:
    init <matter>                 scaffold the vault (refuses a monolith without --migrate)
    new <matter> <type> <title>   create a note from the template
    check <matter> [--fix]        lint: front matter, links, dates, duplicates, index sync
    index <matter>                regenerate KNOWLEDGE.md index and the entity index
    migrate <matter>              split a legacy KNOWLEDGE.md into staging notes for the
                                  migrate-knowledge skill; the legacy file is preserved

Rules the linter enforces: every note has title/type/updated; dates are
absolute ISO dates; no heading is a date or date range (the diary
pattern the single file degenerated into); every wikilink resolves to a
note or a file in the matter; no two notes share an alias; every note
appears in the index; staging notes are a warning until migrated.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

VAULT = "knowledge"
TYPES = ("person", "organization", "event", "topic", "issue", "filing")
TYPE_DIRS = {"person": "people", "organization": "organizations", "event": "events",
             "topic": "topics", "issue": "issues", "filing": "filings"}
STAGING = "_migration"
INDEX_START = "<!-- knowledge-index:start (generated by `sc knowledge index`; edit notes, not this) -->"
INDEX_END = "<!-- knowledge-index:end -->"
MONTHS = ("january", "february", "march", "april", "may", "june", "july", "august",
          "september", "october", "november", "december")
DATE_HEADING = re.compile(r"^#{1,6}\s+(?:(" + "|".join(MONTHS) + r")\b|\d{4}\b|\d{1,2}/\d{1,2}/\d{2,4})", re.I)
RELATIVE_DATES = re.compile(r"\b(yesterday|today|tomorrow|last week|next week|this week|last month|this morning|tonight)\b", re.I)
WIKILINK = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]")
ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def slugify(title: str) -> str:
    s = re.sub(r"[^\w\s-]", "", title.lower()).strip()
    s = re.sub(r"[\s_]+", "-", s)
    return re.sub(r"-{2,}", "-", s).strip("-") or "note"


@dataclass
class Note:
    path: Path
    stem: str
    meta: dict
    body: str
    problems: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def staging(self) -> bool:
        return STAGING in self.path.parts


def split_front_matter(text: str) -> tuple[dict, str, str | None]:
    """(meta, body, error)."""
    if not text.startswith("---\n"):
        return {}, text, "no YAML front matter"
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text, "unterminated front matter"
    raw = text[4:end]
    try:
        meta = yaml.safe_load(raw) or {}
    except yaml.YAMLError as exc:
        return {}, text[end + 4:], f"front matter is not valid YAML: {str(exc).splitlines()[0]}"
    if not isinstance(meta, dict):
        return {}, text[end + 4:], "front matter is not a mapping"
    return meta, text[end + 4:].lstrip("\n"), None


def load_notes(matter: Path) -> list[Note]:
    root = matter / VAULT
    notes: list[Note] = []
    if not root.is_dir():
        return notes
    for p in sorted(root.rglob("*.md")):
        if p.name == "README.md" and p.parent == root:
            continue
        if p.name.startswith(".") or p.name == "KNOWLEDGE.legacy.md":
            continue
        meta, body, err = split_front_matter(p.read_text(encoding="utf-8", errors="replace"))
        n = Note(path=p, stem=p.stem, meta=meta, body=body)
        if err:
            n.problems.append(err)
        notes.append(n)
    return notes


def _as_list(v) -> list:
    if v is None:
        return []
    if isinstance(v, (list, tuple)):
        return list(v)
    return [v]


def _link_targets(text: str) -> list[str]:
    return [m.group(1).strip() for m in WIKILINK.finditer(text)]


def check(matter: Path, notes: list[Note] | None = None) -> list[Note]:
    matter = Path(os.path.abspath(matter))
    notes = notes if notes is not None else load_notes(matter)
    stems = {n.stem.lower(): n for n in notes}
    alias_owner: dict[str, str] = {}
    inbound: dict[str, int] = {n.stem.lower(): 0 for n in notes}
    for n in notes:
        m = n.meta
        if not m.get("title"):
            n.problems.append("missing title")
        t = m.get("type")
        if t not in TYPES:
            n.problems.append(f"type must be one of {TYPES}, got {t!r}")
        elif not n.staging and n.path.parent.name != TYPE_DIRS[t]:
            n.warnings.append(f"type {t} notes live in {VAULT}/{TYPE_DIRS[t]}/")
        upd = str(m.get("updated", ""))
        if not ISO_DATE.match(upd):
            n.problems.append(f"updated must be an absolute YYYY-MM-DD date, got {upd!r}")
        if t == "event":
            d = str(m.get("date", ""))
            if not ISO_DATE.match(d):
                n.problems.append("an event note needs date: YYYY-MM-DD")
        if t == "issue" and m.get("status") not in ("open", "resolved"):
            n.problems.append("an issue note needs status: open | resolved")
        if m.get("verified") not in ("machine", "human"):
            n.warnings.append("verified: should be machine or human")
        for key in ("aliases", "tags", "related"):
            if key in m and not isinstance(m[key], list):
                n.problems.append(f"{key} must be a list")
        for a in _as_list(m.get("aliases")) + [m.get("title") or ""]:
            a_l = str(a).strip().lower()
            if not a_l:
                continue
            if a_l in alias_owner and alias_owner[a_l] != n.stem:
                n.problems.append(f"alias {a!r} is also claimed by [[{alias_owner[a_l]}]]")
            alias_owner.setdefault(a_l, n.stem)
        if not _as_list(m.get("aliases")) and t in ("person", "organization"):
            n.warnings.append("no aliases: the record will not be grepped for name variants")
        for s in _as_list(m.get("sources")):
            if not isinstance(s, dict) or "path" not in s:
                n.problems.append(f"source entries need a path: {s!r}")
            elif not (matter / str(s["path"])).exists():
                n.problems.append(f"source path does not exist: {s['path']}")
        for ln in n.body.splitlines():
            if DATE_HEADING.match(ln):
                msg = f"heading is a date (the diary pattern): {ln.strip()[:60]!r}"
                (n.warnings if n.staging else n.problems).append(msg)
        for mm in RELATIVE_DATES.finditer(n.body):
            n.warnings.append(f"relative date {mm.group(0)!r}: write the absolute date")
            break
        for target in _link_targets(n.body) + [str(x) for x in _as_list(m.get("related"))]:
            tgt = target
            for mm in WIKILINK.finditer(tgt):
                tgt = mm.group(1).strip()
            key = tgt.lower()
            if key in stems:
                if key != n.stem.lower():
                    inbound[key] += 1
            elif (matter / tgt).exists():
                pass
            else:
                n.problems.append(f"link does not resolve: [[{tgt}]]")
        if n.staging:
            n.warnings.append("staging note from a legacy KNOWLEDGE.md; finish the migrate-knowledge skill")
    for n in notes:
        if not n.staging and inbound.get(n.stem.lower(), 0) == 0 and len(notes) > 1:
            n.warnings.append("orphan: no other note links here")
    # index sync
    idx = matter / "KNOWLEDGE.md"
    if idx.exists() and notes:
        text = idx.read_text(encoding="utf-8", errors="replace")
        if INDEX_START not in text:
            for n in notes[:1]:
                n.problems.append("KNOWLEDGE.md has no index markers; run `sc knowledge index`")
        else:
            block = text.split(INDEX_START, 1)[1].split(INDEX_END, 1)[0]
            for n in notes:
                if not n.staging and f"[[{n.stem}]]" not in block:
                    n.problems.append("not in the KNOWLEDGE.md index; run `sc knowledge index`")
    return notes


def render_index(matter: Path, notes: list[Note]) -> str:
    lines = [INDEX_START, ""]
    by_type: dict[str, list[Note]] = {}
    for n in notes:
        if n.staging:
            continue
        by_type.setdefault(str(n.meta.get("type", "topic")), []).append(n)
    for t in TYPES:
        group = sorted(by_type.get(t, []), key=lambda n: str(n.meta.get("date") or n.meta.get("title") or n.stem))
        if not group:
            continue
        lines.append(f"## {TYPE_DIRS[t].capitalize()} ({len(group)})")
        lines.append("")
        for n in group:
            extra = []
            if t == "event" and n.meta.get("date"):
                extra.append(str(n.meta["date"]))
            if t == "issue":
                extra.append(str(n.meta.get("status", "")))
            extra.append(f"updated {n.meta.get('updated', '?')}")
            ns = len(_as_list(n.meta.get("sources")))
            if ns:
                extra.append(f"{ns} source{'s' if ns != 1 else ''}")
            lines.append(f"- [[{n.stem}]] --- {n.meta.get('title', n.stem)} ({'; '.join(extra)})")
        lines.append("")
    staging = [n for n in notes if n.staging]
    if staging:
        lines.append(f"## Migration staging ({len(staging)} notes awaiting the migrate-knowledge skill)")
        lines.append("")
        for n in staging:
            lines.append(f"- [[{n.stem}]] --- {n.meta.get('title', n.stem)}")
        lines.append("")
    lines.append(INDEX_END)
    return "\n".join(lines)


def write_index(matter: Path, notes: list[Note]) -> Path:
    matter = Path(os.path.abspath(matter))
    idx = matter / "KNOWLEDGE.md"
    generated = render_index(matter, notes)
    if idx.exists():
        text = idx.read_text(encoding="utf-8", errors="replace")
        if INDEX_START in text and INDEX_END in text:
            head = text.split(INDEX_START, 1)[0]
            tail = text.split(INDEX_END, 1)[1]
            text = head + generated + tail
        else:
            text = text.rstrip("\n") + "\n\n" + generated + "\n"
    else:
        text = index_preamble(matter.name) + "\n" + generated + "\n"
    idx.write_text(text, encoding="utf-8")
    # derived entity index
    ent: dict = {"notes": {}, "aliases": {}}
    for n in notes:
        rel = str(n.path.relative_to(matter))
        ent["notes"][n.stem] = {"title": n.meta.get("title"), "type": n.meta.get("type"),
                                "path": rel, "updated": str(n.meta.get("updated", "")),
                                "staging": n.staging}
        for a in [n.meta.get("title") or ""] + [str(x) for x in _as_list(n.meta.get("aliases"))]:
            a_l = a.strip().lower()
            if a_l:
                ent["aliases"].setdefault(a_l, []).append(n.stem)
    out = matter / "derived" / "knowledge" / "entities.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(ent, indent=1, sort_keys=True), encoding="utf-8")
    return idx


def index_preamble(name: str) -> str:
    return f"""# KNOWLEDGE --- index of the {name} knowledge vault

Durable case knowledge lives in `knowledge/`, one note per person,
organization, event, topic, issue or filing, each with front matter
(`aliases`, `tags`, `related`, `sources`, `updated`). Read the note you
need, not this file. Open the matter directory as an Obsidian vault for
backlinks and the graph; nothing depends on Obsidian. `sc knowledge new`
creates a note, `sc knowledge check` lints the vault, `sc knowledge
index` regenerates the list below. See ADR-0043.
"""


NOTE_TEMPLATE = """---
title: {title}
type: {type}
aliases: []
tags: []
related: []
sources: []
{extra}updated: {today}
verified: machine
---

# {title}

(What is established, with absolute dates and a source for each fact.
Write the names, variants and misspellings the record actually uses so
ripgrep finds this note. No dated headings; events get their own notes.)
"""


def new_note(matter: Path, ntype: str, title: str, aliases: list[str] | None = None) -> Path:
    matter = Path(os.path.abspath(matter))
    if ntype not in TYPES:
        raise SystemExit(f"type must be one of {TYPES}")
    d = matter / VAULT / TYPE_DIRS[ntype]
    d.mkdir(parents=True, exist_ok=True)
    stem = slugify(title)
    p = d / f"{stem}.md"
    if p.exists():
        raise SystemExit(f"{p.relative_to(matter)} already exists")
    extra = ""
    if ntype == "event":
        extra = "date: \n"
    if ntype == "issue":
        extra = "status: open\n"
    text = NOTE_TEMPLATE.format(title=title, type=ntype, extra=extra, today=dt.date.today().isoformat())
    if aliases:
        text = text.replace("aliases: []", "aliases: [" + ", ".join(json.dumps(a) for a in aliases) + "]", 1)
    p.write_text(text, encoding="utf-8")
    return p


README = """# knowledge/ --- the matter's knowledge vault

One note per person, organization, event, topic, issue or filing, in
the folder for its type. Front matter carries `aliases` (every name
variant the record uses, misspellings included), `tags`, `related`
(wikilinks), `sources` (path, pages, note), `updated` (absolute date)
and `verified` (machine | human). Bodies are keyword-dense prose with
absolute dates and no dated headings.

Open the matter directory in Obsidian for backlinks and the graph
(optional; `.obsidian/` is ignored). Tools: `sc knowledge new|check|index`.
The index is `../KNOWLEDGE.md`. `_migration/` holds staging notes split
from a legacy single-file KNOWLEDGE.md until the migrate-knowledge skill
has folded them into real notes.
"""


def init(matter: Path, migrate: bool = False) -> list[str]:
    matter = Path(os.path.abspath(matter))
    out: list[str] = []
    root = matter / VAULT
    legacy = matter / "KNOWLEDGE.md"
    if legacy.exists() and INDEX_START not in legacy.read_text(encoding="utf-8", errors="replace"):
        n_lines = sum(1 for _ in legacy.open(encoding="utf-8", errors="replace"))
        if not migrate:
            raise SystemExit(f"KNOWLEDGE.md is a {n_lines}-line single file; run `sc knowledge migrate` "
                             "(or init --migrate) so it is split into staging notes rather than overwritten")
    for t in TYPES:
        (root / TYPE_DIRS[t]).mkdir(parents=True, exist_ok=True)
    rd = root / "README.md"
    if not rd.exists():
        rd.write_text(README, encoding="utf-8")
        out.append(f"wrote {rd.relative_to(matter)}")
    gi = matter / ".gitignore"
    text = gi.read_text() if gi.exists() else ""
    if ".obsidian/" not in text.splitlines():
        gi.write_text(text.rstrip("\n") + ("\n" if text else "") + "\n# Obsidian workspace state (optional viewer for knowledge/)\n.obsidian/\n")
        out.append("appended .obsidian/ to .gitignore")
    if migrate and legacy.exists() and INDEX_START not in legacy.read_text(encoding="utf-8", errors="replace"):
        out += migrate_legacy(matter)
    notes = load_notes(matter)
    write_index(matter, notes)
    out.append("wrote KNOWLEDGE.md index and derived/knowledge/entities.json")
    return out


def _heading_date(heading: str) -> str | None:
    m = re.search(r"(" + "|".join(MONTHS) + r")\s+(\d{1,2})(?:\s*(?:--|-|–|—|to)\s*(?:(" + "|".join(MONTHS) + r")\s+)?(\d{1,2}))?,?\s+(\d{4})", heading, re.I)
    if not m:
        m2 = re.search(r"\b(20\d{2})-(\d{2})-(\d{2})\b", heading)
        return m2.group(0) if m2 else None
    month = MONTHS.index(m.group(1).lower()) + 1
    day = int(m.group(4) or m.group(2))
    year = int(m.group(5))
    try:
        return dt.date(year, month, day).isoformat()
    except ValueError:
        return None


def migrate_legacy(matter: Path) -> list[str]:
    """Split a single-file KNOWLEDGE.md by H2 into staging notes. The
    legacy file is copied whole into the staging directory and is never
    deleted by this tool; KNOWLEDGE.md becomes the index."""
    matter = Path(os.path.abspath(matter))
    legacy = matter / "KNOWLEDGE.md"
    text = legacy.read_text(encoding="utf-8", errors="replace")
    if INDEX_START in text:
        return ["KNOWLEDGE.md is already an index; nothing to migrate"]
    stage = matter / VAULT / STAGING
    stage.mkdir(parents=True, exist_ok=True)
    keep = stage / "KNOWLEDGE.legacy.md"
    out: list[str] = []
    if not keep.exists():
        keep.write_text(text, encoding="utf-8")
        out.append(f"preserved the single file as {keep.relative_to(matter)}")
    # split on H2; the preamble (before the first H2) becomes 00-preamble
    parts = re.split(r"(?m)^(?=## )", text)
    n = 0
    today = dt.date.today().isoformat()
    for i, part in enumerate(parts):
        body = part.strip("\n")
        if not body:
            continue
        first = body.splitlines()[0]
        if first.startswith("## "):
            heading = first[3:].strip()
            body = "\n".join(body.splitlines()[1:]).strip("\n")
        else:
            heading = "Preamble"
        n += 1
        stem = f"{n:02d}-{slugify(heading)[:60]}"
        p = stage / f"{stem}.md"
        if p.exists():
            continue
        when = _heading_date(heading) or today
        meta = {"title": heading, "type": "topic", "aliases": [], "tags": ["migration-staging"],
                "related": [], "sources": [], "updated": when, "verified": "machine",
                "migrated_from": f"KNOWLEDGE.md ## {heading}"}
        fm = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True).rstrip("\n")
        note_body = ("# " + heading + "\n\n" + body + "\n") if heading != "Preamble" else body + "\n"
        # demote any dated H2/H3 inside to plain bold lines so the note passes the linter
        note_body = re.sub(r"(?m)^(#{2,6})\s+(.*)$", lambda m: (f"**{m.group(2).strip()}**" if DATE_HEADING.match(m.group(0)) else m.group(0)), note_body)
        p.write_text(f"---\n{fm}\n---\n\n{note_body}", encoding="utf-8")
    out.append(f"split into {n} staging note(s) under {stage.relative_to(matter)}")
    legacy.write_text(index_preamble(matter.name) + f"""
**Migration in progress.** The former single file is preserved at
`knowledge/_migration/KNOWLEDGE.legacy.md` and split into staging notes
under `knowledge/_migration/`. Run the `migrate-knowledge` skill to fold
them into real notes, then `sc knowledge check` must pass and the staging
directory is removed by a human.

""" + INDEX_START + "\n" + INDEX_END + "\n", encoding="utf-8")
    out.append("KNOWLEDGE.md is now the index (legacy text preserved)")
    return out


def format_check(notes: list[Note]) -> str:
    lines: list[str] = []
    errs = sum(len(n.problems) for n in notes)
    warns = sum(len(n.warnings) for n in notes)
    staging = sum(1 for n in notes if n.staging)
    for n in notes:
        for p in n.problems:
            lines.append(f"ERROR {n.path.name}: {p}")
        for w in n.warnings:
            lines.append(f"warn  {n.path.name}: {w}")
    lines.append(f"{len(notes)} note(s), {errs} error(s), {warns} warning(s)"
                 + (f", {staging} in migration staging" if staging else ""))
    return "\n".join(lines) + "\n"


def upcoming_events(matter: Path, limit: int = 10) -> list[str]:
    today = dt.date.today().isoformat()
    ev = []
    for n in load_notes(matter):
        if n.meta.get("type") == "event" and str(n.meta.get("date", "")) >= today and not n.staging:
            ev.append((str(n.meta["date"]), f"{n.meta['date']}: {n.meta.get('title', n.stem)} [[{n.stem}]]"))
    return [e[1] for e in sorted(ev)[:limit]]


def open_issues(matter: Path, limit: int = 8) -> list[str]:
    out = []
    for n in load_notes(matter):
        if n.meta.get("type") == "issue" and n.meta.get("status") == "open" and not n.staging:
            out.append(f"{n.meta.get('title', n.stem)} [[{n.stem}]] (updated {n.meta.get('updated', '?')})")
    return out[:limit]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sp = sub.add_parser("init"); sp.add_argument("matter", nargs="?", default="."); sp.add_argument("--migrate", action="store_true")
    sp = sub.add_parser("new"); sp.add_argument("matter"); sp.add_argument("type", choices=TYPES); sp.add_argument("title"); sp.add_argument("--alias", action="append", default=[])
    sp = sub.add_parser("check"); sp.add_argument("matter", nargs="?", default="."); sp.add_argument("--fix", action="store_true", help="regenerate the index first")
    sp = sub.add_parser("index"); sp.add_argument("matter", nargs="?", default=".")
    sp = sub.add_parser("migrate"); sp.add_argument("matter", nargs="?", default=".")
    a = ap.parse_args()
    matter = Path(a.matter)
    if a.cmd == "init":
        print("\n".join(init(matter, migrate=a.migrate))); return 0
    if a.cmd == "new":
        p = new_note(matter, a.type, a.title, a.alias); print(p); write_index(matter, load_notes(matter)); return 0
    if a.cmd == "index":
        print(write_index(matter, load_notes(matter))); return 0
    if a.cmd == "migrate":
        out = migrate_legacy(matter); write_index(matter, load_notes(matter)); print("\n".join(out)); return 0
    if a.cmd == "check":
        if a.fix:
            write_index(matter, load_notes(matter))
        notes = check(matter)
        sys.stdout.write(format_check(notes))
        return 1 if any(n.problems for n in notes) else 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
